eggs:
  stone:
    blocks: 10000
    fortune-boost-min: 1.05
    fortune-boost-max: 1.1
    sell-boost-min: 1.1
    sell-boost-max: 1.2
    color1: "<#6D6D6D>"
    color2: "<#A9A9A9>"
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDBmZDViMmMzM2ViNjJmMDRhODhjNjY5ZjJmNmRhMjVlMjRiYzk0YmE4N2I5N2IwZjhkMjc5M2JmYjdmM2Y1In19fQ=="
  iron:
    blocks: 40000
    fortune-boost-min: 1.1
    fortune-boost-max: 1.5
    sell-boost-min: 1.2
    sell-boost-max: 1.5
    color1: "<#4C4F56>"
    color2: "<#7F858C>"
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTM5YTFjOTBhMzY3YzQ0ZmFhNDlkMGUyNzM0ODc3NzBmMmUzZjgzZGNiMWViYTZkNzU4YjQ3MzBhZTVmOTY4OCJ9fX0="
  gold:
    blocks: 90000
    fortune-boost-min: 1.5
    fortune-boost-max: 2.5
    sell-boost-min: 1.5
    sell-boost-max: 2.0
    color1: "<#B78628>"
    color2: "<#FFD70>"
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTUxNTk5ZjY2ZTgzZGE1NTVjZjliOGI3ZTVhMzc5ZDBkZWFiMjFjMmVlZTkwOWQxODM3MzIzZGIwODkzYmYzOCJ9fX0="
  diamond:
    blocks: 150000
    fortune-boost-min: 2.5
    fortune-boost-max: 3.5
    sell-boost-min: 2.0
    sell-boost-max: 2.5
    color1: "<#3A89C9>"
    color2: "<#85E3FF>"
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzYxMDU1ZDcyZTBhYThhMTYyYjQwNDczZTMwNzQ4ZjczMzExNjcwMGIwNGJlNmFjOWExZTgxNjFjYTc3YWYwYyJ9fX0="
  dragon:
    blocks: 300000
    fortune-boost-min: 3.5
    fortune-boost-max: 5.0
    sell-boost-min: 2.5
    sell-boost-max: 3.5
    lucky-block-nuker-min: 3
    lucky-block-nuker-max: 10
    color1: "<#8B0000>"
    color2: "<#FF4500>"
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWZlYzNlMjQ1NTE3MjZjYjNkNjRjYmQxNjA0YTFhOWY4YTFlMTE2OTM3MjJhOGFhZDUxMDlhMWZmZmE4ZDQzYyJ9fX0="

pets:
  stone:
    lady_bug:
      color1: "#6B4226"
      color2: "#A0522D"
      chance: 0.5
      model: "ladybugicon"
    snail:
      color1: "#4F4F2F"
      color2: "#808060"
      chance: 0.3
      model: "snailicon"
    hedgehog:
      color1: "#4A2C2A"
      color2: "#8B4513"
      chance: 0.15
      model: "hedgehogicon"
    white_rabbit:
      color1: "#DCDCDC"
      color2: "#F5F5F5"
      chance: 0.04
      model: "rabbit2icon"
    brown_rabbit:
      color1: "#8B4513"
      color2: "#CD853F"
      chance: 0.01
      model: "rabbiticon"
  iron:
    opossum:
      color1: "#696969"
      color2: "#A9A9A9"
      chance: 0.5
      model: "opossumicon"
    seal:
      color1: "#556B2F"
      color2: "#6B8E23"
      chance: 0.3
      model: "seal_harboricon"
    badger:
      color1: "#333333"
      color2: "#BEBEBE"
      chance: 0.15
      model: "badgericon"
    beaver:
      color1: "#8B4513"
      color2: "#DEB887"
      chance: 0.045
      model: "beavericon"
    turtle:
      color1: "#2E8B57"
      color2: "#66CDAA"
      chance: 0.004
      model: "turtle_baseicon"
    crocodile:
      color1: "#556B2F"
      color2: "#6B8E23"
      chance: 0.001
      model: "crocodileicon"
  gold:
    deer:
      color1: "#8B4513"
      color2: "#F4A460"
      chance: 0.5
      model: "female_deericon"
    gazelle:
      color1: "#D2691E"
      color2: "#FF8C00"
      chance: 0.3
      model: "gazelleicon"
    red_panda:
      color1: "#8B0000"
      color2: "#FF4500"
      chance: 0.15
      model: "red_pandaicon"
    bison:
      color1: "#5E2605"
      color2: "#A0522D"
      chance: 0.04
      model: "bisonicon"
    lion:
      color1: "#FFD700"
      color2: "#FFE135"
      chance: 0.01
      model: "lionicon"
  diamond:
    arctic_fox:
      color1: "#B0C4DE"
      color2: "#DCDCDC"
      chance: 0.5
      model: "fox_articicon"
    narwhal:
      color1: "#4682B4"
      color2: "#87CEFA"
      chance: 0.3
      model: "narwhalicon"
    pegasus:
      color1: "#5F9EA0"
      color2: "#AFEEEE"
      chance: 0.15
      model: "pegasusicon"
    griffin:
      color1: "#778899"
      color2: "#D3D3D3"
      chance: 0.04
      model: "griffinicon"
    unicorn:
      color1: "#8A2BE2"
      color2: "#DA70D6"
      chance: 0.01
      model: "unicornicon"
  dragon:
    killer_whale:
      color1: "#000000"
      color2: "#1E90FF"
      chance: 0.5
      model: "whale_killericon"
    hippogriff:
      color1: "#8B4513"
      color2: "#CD853F"
      chance: 0.3
      model: "hippogrifficon"
    hippocampus:
      color1: "#2E8B57"
      color2: "#66CDAA"
      chance: 0.15
      model: "hippocampusicon"
    silver_dragon:
      color1: "#C0C0C0"
      color2: "#E5E5E5"
      chance: 0.04
      model: "dragon_silvericon"
    red_dragon:
      color1: "#8B0000"
      color2: "#FF4500"
      chance: 0.01
      model: "dragon_redicon"
    black_dragon:
      color1: "#000000"
      color2: "#696969"
      chance: 0.01
      model: "dragon_blackicon"

levels:
  1: 250
  2: 350
  3: 500
  4: 750
  5: 1000
  6: 1200
  7: 1500
  8: 2000
  9: 3500
  10: 4000
  11: 4500
  12: 5000
  13: 5500
  14: 6000
  15: 6500
  16: 7500
  17: 8000
  18: 8500
  19: 9000
  20: 9500
  21: 10000
  22: 11000
  23: 12000
  24: 13000
  25: 14000
  26: 15000
  27: 16000
  28: 17000
  29: 18000
  30: 19000
  31: 20000
  32: 21000
  33: 22000
  34: 23000
  35: 24000
  36: 25000
  37: 26000
  38: 27000
  39: 28000
  40: 29000
  41: 30000
  42: 31000
  43: 32000
  44: 33000
  45: 34000
  46: 35000
  47: 36000
  48: 37000
  49: 38000
  50: 39000
  51: 40000
  52: 41000
  53: 42000
  54: 43000
  55: 44000
  56: 45000
  57: 46000
  58: 47000
  59: 48000
  60: 49000
  61: 50000
  62: 55000
  63: 60000
  64: 65000
  65: 70000
  66: 75000
  67: 80000
  68: 85000
  69: 90000
  70: 95000
  71: 100000
  72: 120000
  73: 150000
  74: 190000
  75: 250000
  76: 290000
  77: 360000
  78: 400000
  79: 470000
  80: 500000
  81: 550000
  82: 600000
  83: 650000
  84: 700000
  85: 750000
  86: 800000
  87: 850000
  88: 900000
  89: 950000
  90: 1000000
  91: 1100000
  92: 1200000
  93: 1300000
  94: 1400000
  95: 1500000
  96: 1600000
  97: 1700000
  98: 1800000
  99: 1900000
  100: 2000000