eggs:
  stone:
    blocks: 10000
    fortune-boost-min: 1.05
    fortune-boost-max: 1.1
    sell-boost-min: 1.1
    sell-boost-max: 1.2
    color1: "<#6D6D6D>"
    color2: "<#A9A9A9>"
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDBmZDViMmMzM2ViNjJmMDRhODhjNjY5ZjJmNmRhMjVlMjRiYzk0YmE4N2I5N2IwZjhkMjc5M2JmYjdmM2Y1In19fQ=="
  iron:
    blocks: 40000
    fortune-boost-min: 1.1
    fortune-boost-max: 1.5
    sell-boost-min: 1.2
    sell-boost-max: 1.5
    color1: "<#4C4F56>"
    color2: "<#7F858C>"
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTM5YTFjOTBhMzY3YzQ0ZmFhNDlkMGUyNzM0ODc3NzBmMmUzZjgzZGNiMWViYTZkNzU4YjQ3MzBhZTVmOTY4OCJ9fX0="
  gold:
    blocks: 90000
    fortune-boost-min: 1.5
    fortune-boost-max: 2.5
    sell-boost-min: 1.5
    sell-boost-max: 2.0
    color1: "<#B78628>"
    color2: "<#FFD70>"
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTUxNTk5ZjY2ZTgzZGE1NTVjZjliOGI3ZTVhMzc5ZDBkZWFiMjFjMmVlZTkwOWQxODM3MzIzZGIwODkzYmYzOCJ9fX0="
  diamond:
    blocks: 150000
    fortune-boost-min: 2.5
    fortune-boost-max: 3.5
    sell-boost-min: 2.0
    sell-boost-max: 2.5
    color1: "<#3A89C9>"
    color2: "<#85E3FF>"
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzYxMDU1ZDcyZTBhYThhMTYyYjQwNDczZTMwNzQ4ZjczMzExNjcwMGIwNGJlNmFjOWExZTgxNjFjYTc3YWYwYyJ9fX0="
  dragon:
    blocks: 300000
    fortune-boost-min: 3.5
    fortune-boost-max: 5.0
    sell-boost-min: 2.5
    sell-boost-max: 3.5
    lucky-block-nuker-min: 3
    lucky-block-nuker-max: 10
    color1: "<#8B0000>"
    color2: "<#FF4500>"
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWZlYzNlMjQ1NTE3MjZjYjNkNjRjYmQxNjA0YTFhOWY4YTFlMTE2OTM3MjJhOGFhZDUxMDlhMWZmZmE4ZDQzYyJ9fX0="

pets:
  stone:
    lady_bug:
      color1: "<#A05266>"
      color2: "<#C1877D>"
      chance: 0.5
      model: "ladybugicon"
    snail:
      color1: "<#7F7F5F>"
      color2: "<#B0B090>"
      chance: 0.3
      model: "snailicon"
    hedgehog:
      color1: "<#7A5C58>"
      color2: "<#C08973>"
      chance: 0.15
      model: "hedgehogicon"
    white_rabbit:
      color1: "<#F0F0F0>"
      color2: "<#FFFFFF>"
      chance: 0.04
      model: "rabbit2icon"
    brown_rabbit:
      color1: "<#C37A60>"
      color2: "<#E6A87A>"
      chance: 0.01
      model: "rabbiticon"
  iron:
    opossum:
      color1: "<#A9A9A9>"
      color2: "<#CFCFCF>"
      chance: 0.5
      model: "opossumicon"
    seal:
      color1: "<#8CA863>"
      color2: "<#A4C479>"
      chance: 0.3
      model: "seal_harboricon"
    badger:
      color1: "<#666666>"
      color2: "<#D0D0D0>"
      chance: 0.15
      model: "badgericon"
    beaver:
      color1: "<#C08973>"
      color2: "<#EED6B5>"
      chance: 0.045
      model: "beavericon"
    turtle:
      color1: "<#5FBF8D>"
      color2: "<#8FF1BF>"
      chance: 0.004
      model: "turtle_baseicon"
    crocodile:
      color1: "<#8CA863>"
      color2: "<#A4C479>"
      chance: 0.001
      model: "crocodileicon"
  gold:
    deer:
      color1: "<#C08973>"
      color2: "<#F4C29E>"
      chance: 0.5
      model: "female_deericon"
    gazelle:
      color1: "<#E0A265>"
      color2: "<#FFB870>"
      chance: 0.3
      model: "gazelleicon"
    red_panda:
      color1: "<#E07575>"
      color2: "<#FF9C6A>"
      chance: 0.15
      model: "red_pandaicon"
    bison:
      color1: "<#996746>"
      color2: "<#C08973>"
      chance: 0.04
      model: "bisonicon"
    lion:
      color1: "<#FFE680>"
      color2: "<#FFF7A0>"
      chance: 0.01
      model: "lionicon"
  diamond:
    arctic_fox:
      color1: "<#DCE4F5>"
      color2: "<#F5F5F5>"
      chance: 0.5
      model: "fox_articicon"
    narwhal:
      color1: "<#85A3D0>"
      color2: "<#B2D8FF>"
      chance: 0.3
      model: "narwhalicon"
    pegasus:
      color1: "<#8EC4BA>"
      color2: "<#CFF2E7>"
      chance: 0.15
      model: "pegasusicon"
    griffin:
      color1: "<#A3B1C4>"
      color2: "<#DDE0E5>"
      chance: 0.04
      model: "griffinicon"
    unicorn:
      color1: "<#BC88D9>"
      color2: "<#E5A8EC>"
      chance: 0.01
      model: "unicornicon"
  dragon:
    killer_whale:
      color1: "<#85C7FF>"
      color2: "<#B2E8FF>"
      chance: 0.5
      model: "whale_killericon"
    hippogriff:
      color1: "<#C08973>"
      color2: "<#E7BFA8>"
      chance: 0.3
      model: "hippogrifficon"
    hippocampus:
      color1: "<#5FBF8D>"
      color2: "<#8FF1BF>"
      chance: 0.15
      model: "hippocampusicon"
    silver_dragon:
      color1: "<#E5E5E5>"
      color2: "<#F2F2F2>"
      chance: 0.04
      model: "dragon_silvericon"
    red_dragon:
      color1: "<#E07575>"
      color2: "<#FF9C6A>"
      chance: 0.01
      model: "dragon_redicon"
    black_dragon:
      color1: "<#969696>"
      color2: "<#D3D3D3>"
      chance: 0.01
      model: "dragon_blackicon"

levels:
  1: 250
  2: 350
  3: 500
  4: 750
  5: 1000
  6: 1200
  7: 1500
  8: 2000
  9: 3500
  10: 4000
  11: 4500
  12: 5000
  13: 5500
  14: 6000
  15: 6500
  16: 7500
  17: 8000
  18: 8500
  19: 9000
  20: 9500
  21: 10000
  22: 11000
  23: 12000
  24: 13000
  25: 14000
  26: 15000
  27: 16000
  28: 17000
  29: 18000
  30: 19000
  31: 20000
  32: 21000
  33: 22000
  34: 23000
  35: 24000
  36: 25000
  37: 26000
  38: 27000
  39: 28000
  40: 29000
  41: 30000
  42: 31000
  43: 32000
  44: 33000
  45: 34000
  46: 35000
  47: 36000
  48: 37000
  49: 38000
  50: 39000
  51: 40000
  52: 41000
  53: 42000
  54: 43000
  55: 44000
  56: 45000
  57: 46000
  58: 47000
  59: 48000
  60: 49000
  61: 50000
  62: 55000
  63: 60000
  64: 65000
  65: 70000
  66: 75000
  67: 80000
  68: 85000
  69: 90000
  70: 95000
  71: 100000
  72: 120000
  73: 150000
  74: 190000
  75: 250000
  76: 290000
  77: 360000
  78: 400000
  79: 470000
  80: 500000
  81: 550000
  82: 600000
  83: 650000
  84: 700000
  85: 750000
  86: 800000
  87: 850000
  88: 900000
  89: 950000
  90: 1000000
  91: 1100000
  92: 1200000
  93: 1300000
  94: 1400000
  95: 1500000
  96: 1600000
  97: 1700000
  98: 1800000
  99: 1900000
  100: 2000000